-- 1. TABLA DE RECETAS (Con lógica de 90 días y traspaso)
CREATE TABLE recetas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  creado_el TIMESTAMPTZ DEFAULT NOW(),
  borrado_el TIMESTAMPTZ DEFAULT NULL, 
  titulo TEXT NOT NULL,
  ingredientes JSONB, 
  instrucciones TEXT,
  url_imagen TEXT,
  es_ia BOOLEAN DEFAULT TRUE,
  es_publica BOOLEAN DEFAULT FALSE, 
  usuario_id UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

-- 2. TABLA DE PERFILES (Con periodo de gracia para la cuenta)
CREATE TABLE perfiles (
  id UUID REFERENCES auth.users(id) PRIMARY KEY,
  nombre_usuario TEXT UNIQUE,
  url_avatar TEXT,
  biografia TEXT,
  actualizado_el TIMESTAMPTZ DEFAULT NOW(),
  cuenta_eliminada_el TIMESTAMPTZ DEFAULT NULL 
);

-- 3. VISTA PARA EL FRONTEND (Solo recetas que NO están en la papelera)
-- Esto evita que tu amigo tenga que filtrar siempre por 'borrado_el IS NULL'
CREATE OR REPLACE VIEW recetas_activas AS
SELECT * FROM recetas
WHERE borrado_el IS NULL;

-- 4. ROBOT AUTOMÁTICO (Con 'fallback' para el nombre de usuario)
-- Si el registro no trae 'username', le asigna uno automático: chef_xxxx
CREATE OR REPLACE FUNCTION public.gestionar_nuevo_usuario()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.perfiles (id, nombre_usuario)
  VALUES (
    new.id, 
    COALESCE(new.raw_user_meta_data->>'username', 'chef_' || substr(new.id::text, 1, 8))
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Borramos el trigger si existía y lo recreamos
DROP TRIGGER IF EXISTS al_crear_usuario_en_auth ON auth.users;
CREATE TRIGGER al_crear_usuario_en_auth
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.gestionar_nuevo_usuario();

-- 5. BLINDAJE DE SEGURIDAD (RLS - Row Level Security)
-- Activamos la seguridad en las tablas
ALTER TABLE recetas ENABLE ROW LEVEL SECURITY;
ALTER TABLE perfiles ENABLE ROW LEVEL SECURITY;

-- POLÍTICAS PARA RECETAS
CREATE POLICY "Recetas públicas visibles para todos" ON recetas
  FOR SELECT USING (es_publica = TRUE AND borrado_el IS NULL);

CREATE POLICY "Propietario tiene control total de sus recetas" ON recetas
  FOR ALL USING (auth.uid() = usuario_id);

-- POLÍTICAS PARA PERFILES
CREATE POLICY "Perfiles visibles para todos" ON perfiles
  FOR SELECT USING (TRUE);

CREATE POLICY "Usuario solo puede editar su propio perfil" ON perfiles
  FOR UPDATE USING (auth.uid() = id);

------------------------------------------------------------------------------------------

ALTER TABLE recetas DISABLE ROW LEVEL SECURITY;
ALTER TABLE perfiles DISABLE ROW LEVEL SECURITY;

------------------------------------------------------------------------------------------

ALTER TABLE recetas 
ADD COLUMN calories TEXT,
ADD COLUMN tiempo TEXT;

------------------------------------------------------------------------------------------